var data={
    "AF":["阿富汗","Afghanistan","AFG"],
    "AX":["奥兰群岛","Aland Islands","ALA"],
    "AL":["阿尔巴尼亚","Albania","ALB"],
    "DZ":["阿尔及利亚","Algeria","DZA"],
    "AS":["美属萨摩亚","American Samoa","ASM"],
    "AD":["安道尔","Andorra","AND"],
    "AO":["安哥拉","Angola","AGO"],
    "AI":["安圭拉","Anguilla","AIA"],
    "AQ":["南极洲","Antarctica","ATA"],
    "AG":["安提瓜和巴布达","Antigua and Barbuda","ATG"],
    "AR":["阿根廷","Argentina","ARG"],
    "AM":["亚美尼亚","Armenia","ARM"],
    "AW":["阿鲁巴","Aruba","ABW"],
    "AU":["澳大利亚","Australia","AUS"],
    "AT":["奥地利","Austria","AUT"],
    "AZ":["阿塞拜疆","Azerbaijan","AZE"],
    "BS":["巴哈马","Bahamas (The)","BHS"],
    "BH":["巴林","Bahrain","BHR"],
    "BD":["孟加拉国","Bangladesh","BGD"],
    "BB":["巴巴多斯","Barbados","BRB"],
    "BY":["白俄罗斯","Belarus","BLR"],
    "BE":["比利时","Belgium","BEL"],
    "BZ":["伯利兹","Belize","BLZ"],
    "BJ":["贝宁","Benin","BEN"],
    "BM":["百慕大","Bermuda","BMU"],
    "BT":["不丹","Bhutan","BTN"],
    "BO":["玻利维亚","Bolivia","BOL"],
    "BA":["波黑","Bosnia and Herzegovina","BIH"],
    "BW":["博茨瓦纳","Botswana","BWA"],
    "BV":["布维岛","Bouvet Island","BVT"],
    "BR":["巴西","Brazil","BRA"],
    "IO":["英属印度洋领地","British Indian Ocean Territory (the)","IOT"],
    "BN":["文莱","Brunei Darussalam","BRN"],
    "BG":["保加利亚","Bulgaria","BGR"],
    "BF":["布基纳法索","Burkina Faso","BFA"],
    "BI":["布隆迪","Burundi","BDI"],
    "KH":["柬埔寨","Cambodia","KHM"],
    "CM":["喀麦隆","Cameroon","CMR"],
    "CA":["加拿大","Canada","CAN"],
    "CV":["佛得角","Cape Verde","CPV"],
    "KY":["开曼群岛","Cayman Islands (the)","CYM"],
    "CF":["中非","Central African Republic (the)","CAF"],
    "TD":["乍得","Chad","TCD"],
    "CL":["智利","Chile","CHL"],
    "CN":["中国","China","CHN"],
    "CX":["圣诞岛","Christmas Island","CXR"],
    "CC":["科科斯（基林）群岛","Cocos (Keeling) Islands (the)","CCK"],
    "CO":["哥伦比亚","Colombia","COL"],
    "KM":["科摩罗","Comoros","COM"],
    "CG":["刚果（布）","Congo","COG"],
    "CD":["刚果（金）","Congo (the Democratic Republic of the)","COD"],
    "CK":["库克群岛","Cook Islands (the)","COK"],
    "CR":["哥斯达黎加","Costa Rica","CRI"],
    "CI":["科特迪瓦","Côte d'Ivoire","CIV"],
    "HR":["克罗地亚","Croatia","HRV"],
    "CU":["古巴","Cuba","CUB"],
    "CY":["塞浦路斯","Cyprus","CYP"],
    "CZ":["捷克","Czech Republic (the)","CZE"],
    "DK":["丹麦","Denmark","DNK"],
    "DJ":["吉布提","Djibouti","DJI"],
    "DM":["多米尼克","Dominica","DMA"],
    "DO":["多米尼加","Dominican Republic (the)","DOM"],
    "EC":["厄瓜多尔","Ecuador","ECU"],
    "EG":["埃及","Egypt","EGY"],
    "SV":["萨尔瓦多","El Salvador","SLV"],
    "GQ":["赤道几内亚","Equatorial Guinea","GNQ"],
    "ER":["厄立特里亚","Eritrea","ERI"],
    "EE":["爱沙尼亚","Estonia","EST"],
    "ET":["埃塞俄比亚","Ethiopia","ETH"],
    "FK":["福克兰群岛（马尔维纳斯）","Falkland Islands (the) [Malvinas]","FLK"],
    "FO":["法罗群岛","Faroe Islands (the)","FRO"],
    "FJ":["斐济","Fiji","FJI"],
    "FI":["芬兰","Finland","FIN"],
    "FR":["法国","France","FRA"],
    "GF":["法属圭亚那","French Guiana","GUF"],
    "PF":["法属波利尼西亚","French Polynesia","PYF"],
    "TF":["法属南部领地","French Southern Territories (the)","ATF"],
    "GA":["加蓬","Gabon","GAB"],
    "GM":["冈比亚","Gambia (The)","GMB"],
    "GE":["格鲁吉亚","Georgia","GEO"],
    "DE":["德国","Germany","DEU"],
    "GH":["加纳","Ghana","GHA"],
    "GI":["直布罗陀","Gibraltar","GIB"],
    "GR":["希腊","Greece","GRC"],
    "GL":["格陵兰","Greenland","GRL"],
    "GD":["格林纳达","Grenada","GRD"],
    "GP":["瓜德罗普","Guadeloupe","GLP"],
    "GU":["关岛","Guam","GUM"],
    "GT":["危地马拉","Guatemala","GTM"],
    "GG":["格恩西岛","Guernsey","GGY"],
    "GN":["几内亚","Guinea","GIN"],
    "GW":["几内亚比绍","Guinea-Bissau","GNB"],
    "GY":["圭亚那","Guyana","GUY"],
    "HT":["海地","Haiti","HTI"],
    "HM":["赫德岛和麦克唐纳岛","Heard Island and McDonald Islands","HMD"],
    "VA":["梵蒂冈","Holy See (the) [Vatican City State]","VAT"],
    "HN":["洪都拉斯","Honduras","HND"],
    "HK":["中国香港","Hong Kong","HKG"],
    "HU":["匈牙利","Hungary","HUN"],
    "IS":["冰岛","Iceland","ISL"],
    "IN":["印度","India","IND"],
    "ID":["印度尼西亚","Indonesia","IDN"],
    "IR":["伊朗","Iran (the Islamic Republic of)","IRN"],
    "IQ":["伊拉克","Iraq","IRQ"],
    "IE":["爱尔兰","Ireland","IRL"],
    "IM":["英国属地曼岛","Isle of Man","IMN"],
    "IL":["以色列","Israel","ISR"],
    "IT":["意大利","Italy","ITA"],
    "JM":["牙买加","Jamaica","JAM"],
    "JP":["日本","Japan","JPN"],
    "JE":["泽西岛","Jersey","JEY"],
    "JO":["约旦","Jordan","JOR"],
    "KZ":["哈萨克斯坦","Kazakhstan","KAZ"],
    "KE":["肯尼亚","Kenya","KEN"],
    "KI":["基里巴斯","Kiribati","KIR"],
    "KP":["朝鲜","Korea (the Democratic People's Republic of)","PRK"],
    "KR":["韩国","Korea (the Republic of)","KOR"],
    "KW":["科威特","Kuwait","KWT"],
    "KG":["吉尔吉斯斯坦","Kyrgyzstan","KGZ"],
    "LA":["老挝","Lao People's Democratic Republic (the)","LAO"],
    "LV":["拉脱维亚","Latvia","LVA"],
    "LB":["黎巴嫩","Lebanon","LBN"],
    "LS":["莱索托","Lesotho","LSO"],
    "LR":["利比里亚","Liberia","LBR"],
    "LY":["利比亚","Libyan Arab Jamahiriya (the)","LBY"],
    "LI":["列支敦士登","Liechtenstein","LIE"],
    "LT":["立陶宛","Lithuania","LTU"],
    "LU":["卢森堡","Luxembourg","LUX"],
    "MO":["中国澳门","Macao","MAC"],
    "MK":["北马其顿","Macedonia (the former Yugoslav Republic of)","MKD"],
    "MG":["马达加斯加","Madagascar","MDG"],
    "MW":["马拉维","Malawi","MWI"],
    "MY":["马来西亚","Malaysia","MYS"],
    "MV":["马尔代夫","Maldives","MDV"],
    "ML":["马里","Mali","MLI"],
    "MT":["马耳他","Malta","MLT"],
    "MH":["马绍尔群岛","Marshall Islands (the)","MHL"],
    "MQ":["马提尼克","Martinique","MTQ"],
    "MR":["毛利塔尼亚","Mauritania","MRT"],
    "MU":["毛里求斯","Mauritius","MUS"],
    "YT":["马约特","Mayotte","MYT"],
    "MX":["墨西哥","Mexico","MEX"],
    "FM":["密克罗尼西亚联邦","Micronesia (the Federated States of)","FSM"],
    "MD":["摩尔多瓦","Moldova (the Republic of)","MDA"],
    "MC":["摩纳哥","Monaco","MCO"],
    "MN":["蒙古","Mongolia","MNG"],
    "ME":["黑山","Montenegro","MNE"],
    "MS":["蒙特塞拉特","Montserrat","MSR"],
    "MA":["摩洛哥","Morocco","MAR"],
    "MZ":["莫桑比克","Mozambique","MOZ"],
    "MM":["缅甸","Myanmar","MMR"],
    "NA":["纳米比亚","Namibia","NAM"],
    "NR":["瑙鲁","Nauru","NRU"],
    "NP":["尼泊尔","Nepal","NPL"],
    "NL":["荷兰","Netherlands (the)","NLD"],
    "AN":["荷属安的列斯","Netherlands Antilles (the)","ANT"],
    "NC":["新喀里多尼亚","New Caledonia","NCL"],
    "NZ":["新西兰","New Zealand","NZL"],
    "NI":["尼加拉瓜","Nicaragua","NIC"],
    "NE":["尼日尔","Niger (the)","NER"],
    "NG":["尼日利亚","Nigeria","NGA"],
    "NU":["纽埃","Niue","NIU"],
    "NF":["诺福克岛","Norfolk Island","NFK"],
    "MP":["北马里亚纳","Northern Mariana Islands (the)","MNP"],
    "NO":["挪威","Norway","NOR"],
    "OM":["阿曼","Oman","OMN"],
    "PK":["巴基斯坦","Pakistan","PAK"],
    "PW":["帕劳","Palau","PLW"],
    "PS":["巴勒斯坦","Palestinian Territory (the Occupied)","PSE"],
    "PA":["巴拿马","Panama","PAN"],
    "PG":["巴布亚新几内亚","Papua New Guinea","PNG"],
    "PY":["巴拉圭","Paraguay","PRY"],
    "PE":["秘鲁","Peru","PER"],
    "PH":["菲律宾","Philippines (the)","PHL"],
    "PN":["皮特凯恩","Pitcairn","PCN"],
    "PL":["波兰","Poland","POL"],
    "PT":["葡萄牙","Portugal","PRT"],
    "PR":["波多黎各","Puerto Rico","PRI"],
    "QA":["卡塔尔","Qatar","QAT"],
    "RE":["留尼汪","Réunion","REU"],
    "RO":["罗马尼亚","Romania","ROU"],
    "RU":["俄罗斯联邦","Russian Federation (the)","RUS"],
    "RW":["卢旺达","Rwanda","RWA"],
    "SH":["圣赫勒拿","Saint Helena","SHN"],
    "KN":["圣基茨和尼维斯","Saint Kitts and Nevis","KNA"],
    "LC":["圣卢西亚","Saint Lucia","LCA"],
    "PM":["圣皮埃尔和密克隆","Saint Pierre and Miquelon","SPM"],
    "VC":["圣文森特和格林纳丁斯","Saint Vincent and the Grenadines","VCT"],
    "WS":["萨摩亚","Samoa","WSM"],
    "SM":["圣马力诺","San Marino","SMR"],
    "ST":["圣多美和普林西比","Sao Tome and Principe","STP"],
    "SA":["沙特阿拉伯","Saudi Arabia","SAU"],
    "SN":["塞内加尔","Senegal","SEN"],
    "RS":["塞尔维亚","Serbia","SRB"],
    "SC":["塞舌尔","Seychelles","SYC"],
    "SL":["塞拉利昂","Sierra Leone","SLE"],
    "SG":["新加坡","Singapore","SGP"],
    "SK":["斯洛伐克","Slovakia","SVK"],
    "SI":["斯洛文尼亚","Slovenia","SVN"],
    "SB":["所罗门群岛","Solomon Islands (the)","SLB"],
    "SO":["索马里","Somalia","SOM"],
    "ZA":["南非","South Africa","ZAF"],
    "GS":["南乔治亚岛和南桑德韦奇岛","South Georgia and the South Sandwich Islands","SGS"],
    "ES":["西班牙","Spain","ESP"],
    "LK":["斯里兰卡","Sri Lanka","LKA"],
    "SD":["苏丹","Sudan (the)","SDN"],
    "SR":["苏里南","Suriname","SUR"],
    "SJ":["斯瓦尔巴岛和扬马延岛","Svalbard and Jan Mayen","SJM"],
    "SZ":["斯威士兰","Swaziland","SWZ"],
    "SE":["瑞典","Sweden","SWE"],
    "CH":["瑞士","Switzerland","CHE"],
    "SY":["叙利亚","Syrian Arab Republic (the)","SYR"],
    "TW":["中国台湾","Taiwan (Province of China)","TWN"],
    "TJ":["塔吉克斯坦","Tajikistan","TJK"],
    "TZ":["坦桑尼亚","Tanzania","United Republic of","TZA"],
    "TH":["泰国","Thailand","THA"],
    "TL":["东帝汶","Timor-Leste","TLS"],
    "TG":["多哥","Togo","TGO"],
    "TK":["托克劳","Tokelau","TKL"],
    "TO":["汤加","Tonga","TON"],
    "TT":["特立尼达和多巴哥","Trinidad and Tobago","TTO"],
    "TN":["突尼斯","Tunisia","TUN"],
    "TR":["土耳其","Turkey","TUR"],
    "TM":["土库曼斯坦","Turkmenistan","TKM"],
    "TC":["特克斯和凯科斯群岛","Turks and Caicos Islands (the)","TCA"],
    "TV":["图瓦卢","Tuvalu","TUV"],
    "UG":["乌干达","Uganda","UGA"],
    "UA":["乌克兰","Ukraine","UKR"],
    "AE":["阿联酋","United Arab Emirates (the)","ARE"],
    "GB":["英国","United Kingdom (the)","GBR"],
    "US":["美国","United States (the)","USA"],
    "UM":["美国本土外小岛屿","United States Minor Outlying Islands (the)","UMI"],
    "UY":["乌拉圭","Uruguay","URY"],
    "UZ":["乌兹别克斯坦","Uzbekistan","UZB"],
    "VU":["瓦努阿图","Vanuatu","VUT"],
    "VE":["委内瑞拉","Venezuela","VEN"],
    "VN":["越南","Viet Nam","VNM"],
    "VG":["英属维尔京群岛","Virgin Islands (British)","VGB"],
    "VI":["美属维尔京群岛","Virgin Islands (U.S.)","VIR"],
    "WF":["瓦利斯和富图纳","Wallis and Futuna","WLF"],
    "EH":["西撒哈拉","Western Sahara","ESH"],
    "YE":["也门","Yemen","YEM"],
    "YU":["南斯拉夫","Yugoslavia","YUG"],
    "ZM":["赞比亚","Zambia","ZMB"],
    "ZW":["津巴布韦","Zimbabwe","ZWE"]
    };

function ISO3166_to_cn (val)
{
    return data[val.toUpperCase()][0];
}